<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>GenAiLearning</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.GenAI" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Pgvector" />
  </ItemGroup>
  <ItemGroup>
    <None Include="certs\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
